# traefik.yaml
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    filename: /etc/traefik/dynamic_conf.yaml
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: xiayanzheng@outlook.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

http:
  routers:
    my-service:
      rule: "Host(`cd.novaspark.io`)"
      service: my-service
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

  services:
    my-service:
      loadBalancer:
        servers:
          - url: "http://changedetection:5000"